cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//src/mypackage/_cpp:boostmodule",
        "@include_boost//:headers",
        "@include_python//:headers",
        "@lib_boost//:libs",
        "@lib_python//:libs"
    ],
)
